### ISSUE TITLE
NIST's ABAC SP 800-162 should be a BibEx reference

### ISSUE THREAD

**Issue by identitymonk** [openid/authzen#301]
NIST's ABAC SP 800-162 mention in the spec is not an hyperlink to the document.

**Comment by identitymonk** [comment]
```
SP.800-162:
    title: Guide to Attribute Based Access Control (ABAC) Definition and Considerations
    target: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-162.pdf
    author:
    - name: Vincent Hu
      role: editor
      org: NIST
    - name: David Ferraiolo
      role: editor
      org: NIST
    - name: Richard Kuhn
      role: editor
      org: NIST
    - name: Adam Schnitzer
      role: editor
      org: BAH
    - name: Kenneth Sandlin
      role: editor
      org: MITRE
    - name: Robert Miller
      role: editor
      org: MITRE
    - name: Karen Scarfone
      role: editor
      org: Scarfone Cybersecurity
    date: 2014
```
